postgres_dw:
    image: postgres:13
    container_name: postgres_dw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data
    networks:
      - frontend

  pgadmin:
    image: dpage/pgadmin4
    container_name: dw_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DW_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DW_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres_dw
    networks:
      - frontend